version: "3.8"

networks:
  auth:

services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hunuec383jdKKKfdsm
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - auth

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6378:6379"
    networks:
      - auth

  auth_service:
    build:
      context: .
    container_name: auth_service
    restart: always
    env_file:
      - .env
    depends_on:
      - auth_db
    ports:
      - "8001:8001"
    volumes:
      - ./:/auth_service
    entrypoint: ["./entrypoint.sh"]
    networks:
      - auth

volumes:
  auth_postgres_data: